import test from "node:test";
import assert from "node:assert/strict";

import {
	compressPrompt,
	compressToTarget,
} from "../prompt-compressor.js";
import type {
	CompressionLevel,
	CompressionResult,
	CompressionOptions,
} from "../prompt-compressor.js";

// ─── Test Fixtures ──────────────────────────────────────────────────────────

const WHITESPACE_HEAVY = `# Section One

Some content here.



Another paragraph here.


Yet another paragraph.



# Section Two

More content.`;

const MARKDOWN_COMMENTS = `# Title

<!-- This is a comment that should be removed -->

Some content here.

<!-- Another
multi-line
comment -->

More content.`;

const HORIZONTAL_RULES = `# Section One

Some content.

---

# Section Two

More content.

***

# Section Three

Final content.`;

const VERBOSE_PROSE = `In order to implement this feature, it is important to note that the following
requirements must be met. Due to the fact that the system operates in real-time,
prior to deployment we need to verify all components. In addition to the main
module, a number of auxiliary services are required. In the event that a service
fails, subsequent to the failure, the system should recover. For the purpose of
monitoring, in accordance with our SLA, with regard to uptime, at this point in
time we achieve 99.9%. On the basis of recent data, in the case of peak traffic,
as mentioned previously, the system scales automatically.`;

const BOILERPLATE_CONTENT = `# Requirements

## Feature A
Must support pagination.

## Feature B
N/A

## Feature C
(none)

## Feature D
(empty)

## Feature E
(not applicable)

## Feature F
Must handle errors gracefully.`;

const DUPLICATE_LINES = `Status: active
Status: active
Status: active
Priority: high
Name: test project
Name: test project`;

const EMPHASIS_CONTENT = `This is **bold text** and this is *italic text*.
Also __underline bold__ and _underline italic_.
Check [this link](https://example.com) and [another](https://test.org).`;

const CODE_BLOCK_CONTENT = `# Setup Guide

In order to configure the system, run the following command:

\`\`\`typescript
const config = {
  debug: true,
  verbose: false,
  timeout: 3000,
};
\`\`\`

Due to the fact that configuration is loaded at startup, prior to
running the application, verify the config file exists.

\`\`\`bash
ls -la config.json
\`\`\`

The following steps complete the setup.`;

const HEADING_CONTENT = `# Main Title

## Subsection A

In order to do something, the following steps are needed.

## Subsection B

More content here with **emphasis** and [a link](https://example.com).

### Sub-subsection

Details here.`;

const REALISTIC_GSD_CONTENT = `# Project: GSD Task Manager

<!-- Generated by GSD v2.1.0 -->

## Decisions

| Decision ID   | Title                        | Status     | Date         |
|---------------|------------------------------|------------|--------------|
| DEC-001       | Use TypeScript               | Approved   | 2024-01-15   |
| DEC-002       | Adopt monorepo               | Approved   | 2024-01-20   |
| DEC-003       | Use node:test                | Approved   | 2024-02-01   |

## Requirements

### Must-Have

In order to support the core workflow, it is important to note that the following
requirements are non-negotiable. Due to the fact that the system must operate in
CI environments, prior to any release, all tests must pass.

- The system must handle concurrent operations
- The system must handle concurrent operations
- Error recovery must be automatic
- Configuration must be file-based
- Configuration must be file-based

### Nice-to-Have

N/A

### Out of Scope

(none)

---

## Implementation Notes

> In accordance with our coding standards, all modules should follow
> the single responsibility principle. With regard to testing, a number of
> integration tests should supplement unit tests.

For the purpose of maintaining code quality, at this point in time we require
100% branch coverage on critical paths. In the event that coverage drops below
the threshold, subsequent to the detection, the CI pipeline should fail.

**Important**: The following constraints apply:
- *Memory usage* must stay under 512MB
- *CPU usage* must not exceed 80% sustained
- Response times under 100ms for the 95th percentile

In addition to the above, the system should support plugin architecture.
As mentioned previously, this was decided in DEC-001.

---

## Status

Status: active
Status: active
Priority: high
Sprint: 14
Sprint: 14
Milestone: v2.1.0`;

const LONG_LINE = "This is a very long line that goes on and on. It contains multiple sentences that discuss various topics. The purpose of this line is to test the truncation functionality. When lines exceed 300 characters, they should be truncated at a sentence boundary. This ensures that the compressed output remains readable. Additional text is added here to make sure we exceed the 300 character limit for testing purposes. Even more text follows to pad the line further.";

const BLOCKQUOTE_CONTENT = `> This is a blockquote
> with multiple lines
> that should have markers removed.

Normal paragraph here.

> Another blockquote.`;

const BULLET_LIST = `Some intro text:

- First item in the list
- Second item in the list
* Third item with star
+ Fourth item with plus
1. Numbered item one
2. Numbered item two

Closing text.`;

// ─── Light Compression Tests ────────────────────────────────────────────────

test("light compression removes extra whitespace", () => {
	const result = compressPrompt(WHITESPACE_HEAVY, { level: "light" });
	assert.ok(result.compressedChars < result.originalChars, "should reduce size");
	assert.ok(!result.content.includes("   \n"), "should not have trailing spaces");
	// Should not have 3+ consecutive blank lines
	assert.ok(!result.content.match(/\n\s*\n\s*\n\s*\n/), "should not have 3+ blank lines");
	assert.equal(result.level, "light");
});

test("light compression removes markdown comments", () => {
	const result = compressPrompt(MARKDOWN_COMMENTS, { level: "light" });
	assert.ok(!result.content.includes("<!--"), "should not contain comment start");
	assert.ok(!result.content.includes("-->"), "should not contain comment end");
	assert.ok(result.content.includes("# Title"), "should preserve heading");
	assert.ok(result.content.includes("Some content here."), "should preserve normal content");
});

test("light compression removes horizontal rules", () => {
	const result = compressPrompt(HORIZONTAL_RULES, { level: "light" });
	assert.ok(!result.content.match(/^---$/m), "should not contain ---");
	assert.ok(!result.content.match(/^\*\*\*$/m), "should not contain ***");
	assert.ok(result.content.includes("# Section One"), "should preserve headings");
	assert.ok(result.content.includes("# Section Two"), "should preserve headings");
});

test("light compression preserves code blocks", () => {
	const result = compressPrompt(CODE_BLOCK_CONTENT, { level: "light" });
	assert.ok(result.content.includes("const config = {"), "should preserve code block content");
	assert.ok(result.content.includes("```typescript"), "should preserve code fence");
	assert.ok(result.content.includes("```bash"), "should preserve code fence");
});

// ─── Moderate Compression Tests ─────────────────────────────────────────────

test("moderate compression abbreviates verbose phrases", () => {
	const result = compressPrompt(VERBOSE_PROSE, { level: "moderate" });
	assert.ok(result.content.includes("To implement"), "should abbreviate 'In order to'");
	assert.ok(result.content.includes("Because"), "should abbreviate 'Due to the fact that'");
	assert.ok(result.content.includes("Before deployment"), "should abbreviate 'Prior to'");
	assert.ok(result.content.includes("Also,"), "should abbreviate 'In addition to'");
	assert.ok(result.content.includes("Several"), "should abbreviate 'A number of'");
	assert.ok(result.content.includes("If"), "should abbreviate 'In the event that'");
	assert.ok(result.content.includes("After"), "should abbreviate 'Subsequent to'");
	assert.ok(!result.content.includes("For the purpose of"), "should abbreviate 'For the purpose of'");
	assert.ok(result.content.includes("Per"), "should abbreviate 'In accordance with'");
	assert.ok(result.content.includes("Re:"), "should abbreviate 'With regard to'");
	assert.ok(result.content.includes("Now"), "should abbreviate 'At this point in time'");
	assert.ok(result.content.includes("Based on"), "should abbreviate 'On the basis of'");
	assert.ok(result.content.includes("(see above)"), "should abbreviate 'As mentioned previously'");
	assert.ok(result.compressedChars < result.originalChars, "should reduce size");
});

test("moderate compression deduplicates consecutive lines", () => {
	const input = "Line one\nLine one\nLine one\nLine two\nLine three\nLine three";
	const result = compressPrompt(input, { level: "moderate" });
	const lines = result.content.split("\n").filter((l) => l.trim() !== "");
	// Count occurrences of "Line one"
	const lineOneCount = lines.filter((l) => l === "Line one").length;
	assert.equal(lineOneCount, 1, "should deduplicate 'Line one'");
	const lineThreeCount = lines.filter((l) => l === "Line three").length;
	assert.equal(lineThreeCount, 1, "should deduplicate 'Line three'");
});

test("moderate compression removes boilerplate", () => {
	const result = compressPrompt(BOILERPLATE_CONTENT, { level: "moderate" });
	assert.ok(!result.content.match(/^\s*N\/A\s*$/m), "should remove N/A lines");
	assert.ok(!result.content.includes("(none)"), "should remove (none)");
	assert.ok(!result.content.includes("(empty)"), "should remove (empty)");
	assert.ok(!result.content.includes("(not applicable)"), "should remove (not applicable)");
	assert.ok(result.content.includes("Must support pagination"), "should keep real content");
	assert.ok(result.content.includes("Must handle errors"), "should keep real content");
});

test("moderate compression collapses table formatting", () => {
	const table = `|   Name   |   Value   |   Status   |
|   foo    |   bar     |   active   |`;
	const result = compressPrompt(table, { level: "moderate" });
	// Should have reduced padding
	assert.ok(result.compressedChars < result.originalChars, "should reduce table padding");
});

// ─── Aggressive Compression Tests ───────────────────────────────────────────

test("aggressive compression removes emphasis and links", () => {
	const result = compressPrompt(EMPHASIS_CONTENT, { level: "aggressive" });
	assert.ok(!result.content.includes("**"), "should remove bold markers");
	assert.ok(!result.content.includes("__"), "should remove underline bold markers");
	assert.ok(result.content.includes("bold text"), "should keep bold text content");
	assert.ok(result.content.includes("italic text"), "should keep italic text content");
	assert.ok(result.content.includes("this link"), "should keep link text");
	assert.ok(!result.content.includes("https://example.com"), "should remove link URLs");
	assert.ok(!result.content.includes("https://test.org"), "should remove link URLs");
});

test("aggressive compression removes bullet markers", () => {
	const result = compressPrompt(BULLET_LIST, { level: "aggressive" });
	assert.ok(!result.content.match(/^- /m), "should remove dash bullets");
	assert.ok(!result.content.match(/^\* /m), "should remove star bullets");
	assert.ok(!result.content.match(/^\+ /m), "should remove plus bullets");
	assert.ok(!result.content.match(/^\d+\. /m), "should remove numbered bullets");
	assert.ok(result.content.includes("First item"), "should keep bullet content");
	assert.ok(result.content.includes("Numbered item"), "should keep numbered content");
});

test("aggressive compression removes blockquote markers", () => {
	const result = compressPrompt(BLOCKQUOTE_CONTENT, { level: "aggressive" });
	assert.ok(!result.content.match(/^> /m), "should remove blockquote markers");
	assert.ok(result.content.includes("This is a blockquote"), "should keep blockquote content");
	assert.ok(result.content.includes("Normal paragraph"), "should keep normal content");
});

test("aggressive compression truncates long lines", () => {
	const result = compressPrompt(LONG_LINE, { level: "aggressive" });
	const lines = result.content.split("\n");
	for (const line of lines) {
		assert.ok(line.length <= 300, `line should be <= 300 chars, got ${line.length}`);
	}
});

test("aggressive compression deduplicates structural patterns", () => {
	const result = compressPrompt(DUPLICATE_LINES, { level: "aggressive" });
	const lines = result.content.split("\n").filter((l) => l.trim() !== "");
	const statusCount = lines.filter((l) => l.includes("Status: active")).length;
	assert.equal(statusCount, 1, "should keep only one Status: active");
	const nameCount = lines.filter((l) => l.includes("Name: test project")).length;
	assert.equal(nameCount, 1, "should keep only one Name: test project");
});

// ─── Preservation Tests ─────────────────────────────────────────────────────

test("code block preservation protects code from compression", () => {
	const result = compressPrompt(CODE_BLOCK_CONTENT, {
		level: "aggressive",
		preserveCodeBlocks: true,
	});
	// Code blocks should be untouched
	assert.ok(result.content.includes("const config = {"), "code block preserved");
	assert.ok(result.content.includes("debug: true,"), "code block details preserved");
	assert.ok(result.content.includes("ls -la config.json"), "bash code block preserved");
	// But surrounding prose should be compressed
	assert.ok(!result.content.includes("In order to"), "prose should be compressed");
	assert.ok(!result.content.includes("Due to the fact that"), "prose should be compressed");
});

test("code block preservation can be disabled", () => {
	const result = compressPrompt(CODE_BLOCK_CONTENT, {
		level: "aggressive",
		preserveCodeBlocks: false,
	});
	// Phrase abbreviation still works on surrounding text
	assert.ok(result.compressedChars < result.originalChars, "should still compress");
});

test("heading preservation keeps headings intact", () => {
	const result = compressPrompt(HEADING_CONTENT, {
		level: "aggressive",
		preserveHeadings: true,
	});
	assert.ok(result.content.includes("# Main Title"), "should preserve h1");
	assert.ok(result.content.includes("## Subsection A"), "should preserve h2");
	assert.ok(result.content.includes("## Subsection B"), "should preserve h2");
	assert.ok(result.content.includes("### Sub-subsection"), "should preserve h3");
});

// ─── compressToTarget Tests ─────────────────────────────────────────────────

test("compressToTarget tries progressively harder levels", () => {
	// Set a target that light compression cannot reach
	const lightResult = compressPrompt(REALISTIC_GSD_CONTENT, { level: "light" });
	const moderateResult = compressPrompt(REALISTIC_GSD_CONTENT, { level: "moderate" });

	// Target between light and moderate results
	const target = Math.floor((lightResult.compressedChars + moderateResult.compressedChars) / 2);
	const result = compressToTarget(REALISTIC_GSD_CONTENT, target);

	// Should have used at least moderate
	assert.ok(
		result.level === "moderate" || result.level === "aggressive",
		`should use moderate or aggressive, got ${result.level}`,
	);
	assert.ok(result.compressedChars <= target, "should meet target");
});

test("compressToTarget returns best effort when target unreachable", () => {
	// Set an impossibly small target
	const result = compressToTarget(REALISTIC_GSD_CONTENT, 10);
	assert.equal(result.level, "aggressive", "should try aggressive as last resort");
	assert.ok(result.compressedChars > 10, "cannot reach impossibly small target");
	assert.ok(
		result.compressedChars < REALISTIC_GSD_CONTENT.length,
		"should still compress as much as possible",
	);
});

test("compressToTarget returns unchanged if already under target", () => {
	const result = compressToTarget("short text", 1000);
	assert.equal(result.content, "short text");
	assert.equal(result.savingsPercent, 0);
	assert.equal(result.transformationsApplied, 0);
});

// ─── Realistic GSD Content Test ─────────────────────────────────────────────

test("realistic GSD content compresses significantly", () => {
	const result = compressPrompt(REALISTIC_GSD_CONTENT, { level: "aggressive" });

	// Should achieve meaningful compression
	assert.ok(result.savingsPercent > 15, `should achieve >15% savings, got ${result.savingsPercent}%`);
	assert.ok(result.transformationsApplied > 3, "should apply multiple transformations");

	// Key content preserved
	assert.ok(result.content.includes("# Project: GSD Task Manager"), "title preserved");
	assert.ok(result.content.includes("DEC-001"), "decision IDs preserved");
	assert.ok(result.content.includes("TypeScript"), "decision content preserved");
	assert.ok(result.content.includes("## Decisions"), "section headings preserved");
	assert.ok(result.content.includes("## Requirements"), "section headings preserved");

	// Comments removed
	assert.ok(!result.content.includes("<!--"), "comments removed");

	// Verbose phrases abbreviated
	assert.ok(!result.content.includes("In order to"), "verbose phrases compressed");
	assert.ok(!result.content.includes("Due to the fact that"), "verbose phrases compressed");

	// Boilerplate removed
	assert.ok(!result.content.match(/^\s*N\/A\s*$/m), "N/A removed");
	assert.ok(!result.content.includes("(none)"), "(none) removed");
});

// ─── Accuracy and Edge Cases ────────────────────────────────────────────────

test("savingsPercent is accurate", () => {
	const result = compressPrompt(VERBOSE_PROSE, { level: "moderate" });
	const expectedPercent =
		Math.round(((result.originalChars - result.compressedChars) / result.originalChars) * 10000) / 100;
	assert.equal(result.savingsPercent, expectedPercent, "savings percent should be accurate");
});

test("empty input returns empty output", () => {
	const result = compressPrompt("", { level: "aggressive" });
	assert.equal(result.content, "");
	assert.equal(result.originalChars, 0);
	assert.equal(result.compressedChars, 0);
	assert.equal(result.savingsPercent, 0);
	assert.equal(result.transformationsApplied, 0);
});

test("already-compressed content is idempotent at same level", () => {
	const first = compressPrompt(VERBOSE_PROSE, { level: "moderate" });
	const second = compressPrompt(first.content, { level: "moderate" });

	assert.equal(first.content, second.content, "double compression should produce same result");
});

test("content with only code blocks is unchanged", () => {
	const codeOnly = "```typescript\nconst x = 1;\nconst y = 2;\n```";
	const result = compressPrompt(codeOnly, {
		level: "aggressive",
		preserveCodeBlocks: true,
	});
	assert.equal(result.content, codeOnly, "code-only content should be unchanged");
});

test("compression result contains correct metadata", () => {
	const result = compressPrompt(VERBOSE_PROSE, { level: "moderate" });
	assert.equal(result.originalChars, VERBOSE_PROSE.length);
	assert.equal(result.compressedChars, result.content.length);
	assert.equal(result.level, "moderate");
	assert.ok(result.transformationsApplied > 0, "should report transformations");
	assert.ok(result.savingsPercent > 0, "should have positive savings");
	assert.ok(result.savingsPercent < 100, "savings should be less than 100%");
});

test("light compression with defaults", () => {
	// Test that default options work (moderate level, preserve headings/code)
	const result = compressPrompt(REALISTIC_GSD_CONTENT);
	assert.equal(result.level, "moderate", "default level should be moderate");
	assert.ok(result.content.includes("# Project:"), "headings preserved by default");
	assert.ok(result.compressedChars < result.originalChars, "should compress");
});

test("multiple code blocks are all preserved", () => {
	const multiCode = `Some text.

\`\`\`js
function a() { return 1; }
\`\`\`

Middle text with **emphasis**.

\`\`\`python
def b():
    return 2
\`\`\`

End text.`;

	const result = compressPrompt(multiCode, {
		level: "aggressive",
		preserveCodeBlocks: true,
	});
	assert.ok(result.content.includes("function a()"), "first code block preserved");
	assert.ok(result.content.includes("def b():"), "second code block preserved");
	assert.ok(result.content.includes("emphasis"), "emphasis text kept (markers removed)");
	assert.ok(!result.content.includes("**emphasis**"), "emphasis markers removed");
});
